# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moomux < Formula
  desc "A tmux session manager TUI"
  homepage "https://github.com/erickgnclvs/moomux"
  version "0.5.39"
  license "MIT"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erickgnclvs/moomux/releases/download/v0.5.39/moomux_darwin_amd64.tar.gz"
      sha256 "1f70cd802777924e346224349e7df863ac0b913fb47af3459178722d0a7e4dcb"

      define_method(:install) do
        bin.install "moomux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erickgnclvs/moomux/releases/download/v0.5.39/moomux_darwin_arm64.tar.gz"
      sha256 "2e1c6c1658d6ab626235db9097e09ca31608cf18f7580b2bc7bbebcddaa9925c"

      define_method(:install) do
        bin.install "moomux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickgnclvs/moomux/releases/download/v0.5.39/moomux_linux_amd64.tar.gz"
      sha256 "fe3ae16b5715f4cd686892871fef8ee8d7fb12436f92dd7f54be1a20a58253e3"
      define_method(:install) do
        bin.install "moomux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickgnclvs/moomux/releases/download/v0.5.39/moomux_linux_arm64.tar.gz"
      sha256 "38365c400ae7b06f25405cafdc23ee54d6e5531b38a6a540fdcc875e297044f3"
      define_method(:install) do
        bin.install "moomux"
      end
    end
  end

  test do
    system "#{bin}/moomux", "--version"
  end
end
